export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"; 
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"; 
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCESS"; 

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST"; 
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL"; 
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCESS"; 

export const ALL_DETAILS_REQUEST = "ALL_DETAILS_REQUEST"; 
export const ALL_DETAILS_FAIL = "ALL_DETAILS_FAIL"; 
export const ALL_DETAILS_SUCCESS = "ALL_DETAILS_SUCESS"; 

export const REVIEW_REQUEST = "REVIEW_REQUEST"; 
export const REVIEW_SUCCESS = "REVIEW_SUCCESS"; 
export const REVIEW_FAIL = "REVIEW_FAIL"; 
export const REVIEW_RESET = "REVIEW_RESET"; 




export const CLEAR_ERRORS = "CLEAR_ERRORS"; 